version: '3.3'
services:
  app.web:
    build:
      context: .
      args:
        env: prod
    networks:
    - default
    ports:
    - 80:80
networks:
  default:
    external:
      name: marketplace-backend_net-frontend
